pipeline
{
    agent 'any'
    parameters
    {
        string (
          defaultValue: 'develop',
          name: 'BRANCH_NAME')
        booleanParam ( 
            defaultValue: false,
            description: '',
            name: 'FORCE_FULL_BUILD')
    }
    environment 
    {
       GIT_BRANCH = 'master'
        ENV = 'NonProd'
    }
    tools
    {
      maven 'm3'
    }
    stages
    {
        stage ('Compile')
        {
            steps 
            {
               sh 'mvn compile'
            }
        }
        stage('Package')
        {
            steps
            {
             sh  'mvn package'
            }
        }
        stage('question')
        {
            steps {
                 input 'Do you want to deploy to production?'
            }
        }
       stage("foo") {
            steps {
                script {
                    env.RELEASE_SCOPE = input message: 'User input required', ok: 'Release!',
                            parameters: [choice(name: 'RELEASE_SCOPE', choices: 'patch\nminor\nmajor', description: 'What is the release scope?')]
                }
                echo "${env.RELEASE_SCOPE}"
            }
       
        
       stage('archive')
        {
            steps
            {
                archiveArtifacts 'target/*.jar'
            }
        }
    }    
}
