pipeline
{
    agent 'any'
    stages
    {
        stage ('Compile')
        {
            steps 
            {
                mvn compile 
                        
            }
         
        }
        stage('Package')
        {
            steps
            {
                mvn package
            }
        }
        
    }    

}
